#lang racket
(require markdown)
(require markdown/display-xexpr)

(define input-file "../source/content/sample_public.md")
(define output-file "../site/sample_public.html")

(define md
  (call-with-input-file input-file
    (lambda (in) (port->string in))))

(define html
  (parse-markdown md))

(define x `(html ()
    (head ()
      (script ((src "static/js/app.js")))
      (link ((rel "stylesheet") (href "static/css/site.css"))))
    (body ()
      (div ((id "before-block"))
        "This appears before the Markdown content")
      ,@html
      (div ((id "after-block"))
        "This appears after the Markdown content")
      )
    (footer ()
      "Generated by Racket")))

(call-with-output-file output-file
  (lambda (out) (display (xexpr->string x) out))
  #:exists 'replace)
(display (xexpr->string (toc html)) )
(printf "Generated ~a\n" output-file)
